function colors=colorstruct
% function colors=colorstruct
% defines a struct variable with fields .Color and .Name for all SVG colors

colors= {struct('Color',[240,248,255],...
'Name', 'aliceblue',...
'Callback',callback),...
struct('Color',[250,235,215],...
'Name', 'antiquewhite',...
'Callback',callback),...
struct('Color',[0,255,255],...
'Name', 'aqua',...
'Callback',callback),...
struct('Color',[127,255,212],...
'Name', 'aquamarine',...
'Callback',callback),...
struct('Color',[240,255,255],...
'Name', 'azure',...
'Callback',callback),...
struct('Color',[245,245,220],...
'Name', 'beige',...
'Callback',callback),...
struct('Color',[255,228,196],...
'Name', 'bisque',...
'Callback',callback),...
struct('Color',[0,0,0],...
'Name', 'black',...
'Callback',callback),...
struct('Color',[255,235,205],...
'Name', 'blanchedalmond',...
'Callback',callback),...
struct('Color',[0,0,255],...
'Name', 'blue',...
'Callback',callback),...
struct('Color',[138,43,226],...
'Name', 'blueviolet',...
'Callback',callback),...
struct('Color',[165,42,42],...
'Name', 'brown',...
'Callback',callback),...
struct('Color',[222,184,135],...
'Name', 'burlywood',...
'Callback',callback),...
struct('Color',[95,158,160],...
'Name', 'cadetblue',...
'Callback',callback),...
struct('Color',[127,255,0],...
'Name', 'chartreuse',...
'Callback',callback),...
struct('Color',[210,105,30],...
'Name', 'chocolate',...
'Callback',callback),...
struct('Color',[255,127,80],...
'Name', 'coral',...
'Callback',callback),...
struct('Color',[100,149,237],...
'Name', 'cornflowerblue',...
'Callback',callback),...
struct('Color',[255,248,220],...
'Name', 'cornsilk',...
'Callback',callback),...
struct('Color',[220,20,60],...
'Name', 'crimson',...
'Callback',callback),...
struct('Color',[0,255,255],...
'Name', 'cyan',...
'Callback',callback),...
struct('Color',[0,0,139],...
'Name', 'darkblue',...
'Callback',callback),...
struct('Color',[0,139,139],...
'Name', 'darkcyan',...
'Callback',callback),...
struct('Color',[184,134,11],...
'Name', 'darkgoldenrod',...
'Callback',callback),...
struct('Color',[169,169,169],...
'Name', 'darkgray',...
'Callback',callback),...
struct('Color',[0,100,0],...
'Name', 'darkgreen',...
'Callback',callback),...
struct('Color',[169,169,169],...
'Name', 'darkgrey',...
'Callback',callback),...
struct('Color',[189,183,107],...
'Name', 'darkkhaki',...
'Callback',callback),...
struct('Color',[139,0,139],...
'Name', 'darkmagenta',...
'Callback',callback),...
struct('Color',[85,107,47],...
'Name', 'darkolivegreen',...
'Callback',callback),...
struct('Color',[255,140,0],...
'Name', 'darkorange',...
'Callback',callback),...
struct('Color',[153,50,204],...
'Name', 'darkorchid',...
'Callback',callback),...
struct('Color',[139,0,0],...
'Name', 'darkred',...
'Callback',callback),...
struct('Color',[233,150,122],...
'Name', 'darksalmon',...
'Callback',callback),...
struct('Color',[143,188,143],...
'Name', 'darkseagreen',...
'Callback',callback),...
struct('Color',[72,61,139],...
'Name', 'darkslateblue',...
'Callback',callback),...
struct('Color',[47,79,79],...
'Name', 'darkslategray',...
'Callback',callback),...
struct('Color',[47,79,79],...
'Name', 'darkslategrey',...
'Callback',callback),...
struct('Color',[0,206,209],...
'Name', 'darkturquoise',...
'Callback',callback),...
struct('Color',[148,0,211],...
'Name', 'darkviolet',...
'Callback',callback),...
struct('Color',[255,20,147],...
'Name', 'deeppink',...
'Callback',callback),...
struct('Color',[0,191,255],...
'Name', 'deepskyblue',...
'Callback',callback),...
struct('Color',[105,105,105],...
'Name', 'dimgray',...
'Callback',callback),...
struct('Color',[105,105,105],...
'Name', 'dimgrey',...
'Callback',callback),...
struct('Color',[30,144,255],...
'Name', 'dodgerblue',...
'Callback',callback),...
struct('Color',[178,34,34],...
'Name', 'firebrick',...
'Callback',callback),...
struct('Color',[255,250,240],...
'Name', 'floralwhite',...
'Callback',callback),...
struct('Color',[34,139,34],...
'Name', 'forestgreen',...
'Callback',callback),...
struct('Color',[255,0,255],...
'Name', 'fuchsia',...
'Callback',callback),...
struct('Color',[220,220,220],...
'Name', 'gainsboro',...
'Callback',callback),...
struct('Color',[248,248,255],...
'Name', 'ghostwhite',...
'Callback',callback),...
struct('Color',[255,215,0],...
'Name', 'gold',...
'Callback',callback),...
struct('Color',[218,165,32],...
'Name', 'goldenrod',...
'Callback',callback),...
struct('Color',[128,128,128],...
'Name', 'gray',...
'Callback',callback),...
struct('Color',[0,128,0],...
'Name', 'green',...
'Callback',callback),...
struct('Color',[173,255,47],...
'Name', 'greenyellow',...
'Callback',callback),...
struct('Color',[128,128,128],...
'Name', 'grey',...
'Callback',callback),...
struct('Color',[240,255,240],...
'Name', 'honeydew',...
'Callback',callback),...
struct('Color',[255,105,180],...
'Name', 'hotpink',...
'Callback',callback),...
struct('Color',[205,92,92],...
'Name', 'indianred',...
'Callback',callback),...
struct('Color',[75,0,130],...
'Name', 'indigo',...
'Callback',callback),...
struct('Color',[255,255,240],...
'Name', 'ivory',...
'Callback',callback),...
struct('Color',[240,230,140],...
'Name', 'khaki',...
'Callback',callback),...
struct('Color',[230,230,250],...
'Name', 'lavender',...
'Callback',callback),...
struct('Color',[255,240,245],...
'Name', 'lavenderblush',...
'Callback',callback),...
struct('Color',[124,252,0],...
'Name', 'lawngreen',...
'Callback',callback),...
struct('Color',[255,250,205],...
'Name', 'lemonchiffon',...
'Callback',callback),...
struct('Color',[173,216,230],...
'Name', 'lightblue',...
'Callback',callback),...
struct('Color',[240,128,128],...
'Name', 'lightcoral',...
'Callback',callback),...
struct('Color',[224,255,255],...
'Name', 'lightcyan',...
'Callback',callback),...
struct('Color',[250,250,210],...
'Name', 'lightgoldenrodyellow',...
'Callback',callback),...
struct('Color',[211,211,211],...
'Name', 'lightgray',...
'Callback',callback),...
struct('Color',[144,238,144],...
'Name', 'lightgreen',...
'Callback',callback),...
struct('Color',[211,211,211],...
'Name', 'lightgrey',...
'Callback',callback),...
struct('Color',[255,182,193],...
'Name', 'lightpink',...
'Callback',callback),...
struct('Color',[255,160,122],...
'Name', 'lightsalmon',...
'Callback',callback),...
struct('Color',[32,178,170],...
'Name', 'lightseagreen',...
'Callback',callback),...
struct('Color',[135,206,250],...
'Name', 'lightskyblue',...
'Callback',callback),...
struct('Color',[119,136,153],...
'Name', 'lightslategray',...
'Callback',callback),...
struct('Color',[119,136,153],...
'Name', 'lightslategrey',...
'Callback',callback),...
struct('Color',[176,196,222],...
'Name', 'lightsteelblue',...
'Callback',callback),...
struct('Color',[255,255,224],...
'Name', 'lightyellow',...
'Callback',callback),...
struct('Color',[0,255,0],...
'Name', 'lime',...
'Callback',callback),...
struct('Color',[50,205,50],...
'Name', 'limegreen',...
'Callback',callback),...
struct('Color',[250,240,230],...
'Name', 'linen',...
'Callback',callback),...
struct('Color',[255,0,255],...
'Name', 'magenta',...
'Callback',callback),...
struct('Color',[128,0,0],...
'Name', 'maroon',...
'Callback',callback),...
struct('Color',[102,205,170],...
'Name', 'mediumaquamarine',...
'Callback',callback),...
struct('Color',[0,0,205],...
'Name', 'mediumblue',...
'Callback',callback),...
struct('Color',[186,85,211],...
'Name', 'mediumorchid',...
'Callback',callback),...
struct('Color',[147,112,219],...
'Name', 'mediumpurple',...
'Callback',callback),...
struct('Color',[60,179,113],...
'Name', 'mediumseagreen',...
'Callback',callback),...
struct('Color',[123,104,238],...
'Name', 'mediumslateblue',...
'Callback',callback),...
struct('Color',[0,250,154],...
'Name', 'mediumspringgreen',...
'Callback',callback),...
struct('Color',[72,209,204],...
'Name', 'mediumturquoise',...
'Callback',callback),...
struct('Color',[199,21,133],...
'Name', 'mediumvioletred',...
'Callback',callback),...
struct('Color',[25,25,112],...
'Name', 'midnightblue',...
'Callback',callback),...
struct('Color',[245,255,250],...
'Name', 'mintcream',...
'Callback',callback),...
struct('Color',[255,228,225],...
'Name', 'mistyrose',...
'Callback',callback),...
struct('Color',[255,228,181],...
'Name', 'moccasin',...
'Callback',callback),...
struct('Color',[255,222,173],...
'Name', 'navajowhite',...
'Callback',callback),...
struct('Color',[0,0,128],...
'Name', 'navy',...
'Callback',callback),...
struct('Color',[253,245,230],...
'Name', 'oldlace',...
'Callback',callback),...
struct('Color',[128,128,0],...
'Name', 'olive',...
'Callback',callback),...
struct('Color',[107,142,35],...
'Name', 'olivedrab',...
'Callback',callback),...
struct('Color',[255,165,0],...
'Name', 'orange',...
'Callback',callback),...
struct('Color',[255,69,0],...
'Name', 'orangered',...
'Callback',callback),...
struct('Color',[218,112,214],...
'Name', 'orchid',...
'Callback',callback),...
struct('Color',[238,232,170],...
'Name', 'palegoldenrod',...
'Callback',callback),...
struct('Color',[152,251,152],...
'Name', 'palegreen',...
'Callback',callback),...
struct('Color',[175,238,238],...
'Name', 'paleturquoise',...
'Callback',callback),...
struct('Color',[219,112,147],...
'Name', 'palevioletred',...
'Callback',callback),...
struct('Color',[255,239,213],...
'Name', 'papayawhip',...
'Callback',callback),...
struct('Color',[255,218,185],...
'Name', 'peachpuff',...
'Callback',callback),...
struct('Color',[205,133,63],...
'Name', 'peru',...
'Callback',callback),...
struct('Color',[255,192,203],...
'Name', 'pink',...
'Callback',callback),...
struct('Color',[221,160,221],...
'Name', 'plum',...
'Callback',callback),...
struct('Color',[176,224,230],...
'Name', 'powderblue',...
'Callback',callback),...
struct('Color',[128,0,128],...
'Name', 'purple',...
'Callback',callback),...
struct('Color',[255,0,0],...
'Name', 'red',...
'Callback',callback),...
struct('Color',[188,143,143],...
'Name', 'rosybrown',...
'Callback',callback),...
struct('Color',[65,105,225],...
'Name', 'royalblue',...
'Callback',callback),...
struct('Color',[139,69,19],...
'Name', 'saddlebrown',...
'Callback',callback),...
struct('Color',[250,128,114],...
'Name', 'salmon',...
'Callback',callback),...
struct('Color',[244,164,96],...
'Name', 'sandybrown',...
'Callback',callback),...
struct('Color',[46,139,87],...
'Name', 'seagreen',...
'Callback',callback),...
struct('Color',[255,245,238],...
'Name', 'seashell',...
'Callback',callback),...
struct('Color',[160,82,45],...
'Name', 'sienna',...
'Callback',callback),...
struct('Color',[192,192,192],...
'Name', 'silver',...
'Callback',callback),...
struct('Color',[135,206,235],...
'Name', 'skyblue',...
'Callback',callback),...
struct('Color',[106,90,205],...
'Name', 'slateblue',...
'Callback',callback),...
struct('Color',[112,128,144],...
'Name', 'slategray',...
'Callback',callback),...
struct('Color',[112,128,144],...
'Name', 'slategrey',...
'Callback',callback),...
struct('Color',[255,250,250],...
'Name', 'snow',...
'Callback',callback),...
struct('Color',[0,255,127],...
'Name', 'springgreen',...
'Callback',callback),...
struct('Color',[70,130,180],...
'Name', 'steelblue',...
'Callback',callback),...
struct('Color',[210,180,140],...
'Name', 'tan',...
'Callback',callback),...
struct('Color',[0,128,128],...
'Name', 'teal',...
'Callback',callback),...
struct('Color',[216,191,216],...
'Name', 'thistle',...
'Callback',callback),...
struct('Color',[255,99,71],...
'Name', 'tomato',...
'Callback',callback),...
struct('Color',[64,224,208],...
'Name', 'turquoise',...
'Callback',callback),...
struct('Color',[238,130,238],...
'Name', 'violet',...
'Callback',callback),...
struct('Color',[245,222,179],...
'Name', 'wheat',...
'Callback',callback),...
struct('Color',[255,255,255],...
'Name', 'white',...
'Callback',callback),...
struct('Color',[245,245,245],...
'Name', 'whitesmoke',...
'Callback',callback),...
struct('Color',[255,255,0],...
'Name', 'yellow',...
'Callback',callback),...
struct('Color',[154,205,50],...
'Name', 'yellowgreen',...
'Callback',callback)};
